sensu_healthchecks:
  {{TTL_SERVICE_NAME}}_{{TTL_SERVICE_SLICE}}_check:
    type: "script"
    name: "{{TTL_SERVICE_NAME}}_{{TTL_SERVICE_SLICE}}_check"
    script: diagnostics_check.ps1
    interval: 60
    alert_after: 60
    realert_every: 0
